package shareversityguifinal2;

import java.util.ArrayList;

/**
 * The `InvestmentType` class is an abstract class representing different investment types such as Low Risk and Startup investments.
 * It provides methods for buying shares, checking investment day range, and managing a list of relevant companies.
 * Subclasses extend this class to define specific investment types by setting the company list.
 * 
 * @author Fran
 */

public abstract class InvestmentType  
{
    protected ArrayList<Company> companyList;
    
    public InvestmentType(ImportedCompanies allCompanies) 
    {
        setCompanyList(allCompanies);
    }
    
    /*
        This method checks if the inputted days are within the range of a CostPerShare history
    */
    public boolean checkInvestDayOutOfRange(Company company, int day)
    {
        boolean check = true;
        if ((day-1) >= 0 && (day-1) <= company.getCostPerShareHistory().size()) // Check if in range
        {
            check = false;
        }
        
        return check;
    }
    
    /*
        This method buys (withdraws from wallet) shares from the selected Company into the Account Portfolio if it passes the checkOverWithdraw & checkInvestDayOutOfRange checks
    */
    public void buyShares(double amount, Company company, Account account, int day)
    {
        account.getWallet().withdraw(amount);
        if (account.getWallet().checkOverWithdraw(amount) == false && checkInvestDayOutOfRange(company, day) == false)
        {
            Investment newInvestment = new Investment(company, amount, company.getCostPerShareHistory().get(day));
            account.getAccountPortfolio().addInvestment(newInvestment);
        }
    };
    
    // get companies generated by CompanyList, and filter companies of the relevant InvestmentType in the HashMap (allCompanies<Company>, InvestmentTypeEnum>)
    // then set the filtered companies to the companyList of the InvestmentType
    public abstract ArrayList<Company> setCompanyList(ImportedCompanies importedCompanies); 

    // Prints companyList of investmentType
    @Override
    public String toString() 
    {
        String out = "";
        
        for (int i=0; i<companyList.size(); i++)
        {
            out += (i+1) + ". " + companyList.get(i).getName() + ", Cost Per Share: $" + companyList.get(i).getCurrentCPS().getCost() + "\n";
        }
        
        return out;
    }
}
