/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package shareversityguifinal2;

import java.awt.CardLayout;
import java.awt.Dimension;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.JComboBox;

/**
 *
 * @author Fran
 */

public class ShareversityGUI extends javax.swing.JFrame 
{
    private static final int WIDTH = 1024;
    private static final int HEIGHT = 764;
    
    /**
     * Creates new form ShareVersityGUI
     */
    public ShareversityGUI() {
        this.cardLayout = new CardLayout();
        Dimension dimension = new Dimension(WIDTH, HEIGHT);
        
        this.setResizable(false);
        this.setPreferredSize(dimension);
        
        initComponents();
        updateDayComboBox();
        
        getContentPane().setLayout(cardLayout);
        getContentPane().add(loginPanel, "loginPanel");
        getContentPane().add(registerPanel, "registerPanel");
        getContentPane().add(portfolioPanel, "portfolioPanel");
        
        cardLayout.show(this.getContentPane(), "loginPanel");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        loginPanel = new javax.swing.JPanel();
        loginLeftPanel = new javax.swing.JPanel();
        Logo = new javax.swing.JLabel();
        loginRightPanel = new javax.swing.JPanel();
        loginLabel = new javax.swing.JLabel();
        loginPasswordLabel = new javax.swing.JLabel();
        loginPasswordTextField = new javax.swing.JTextField();
        loginUsernameLabel = new javax.swing.JLabel();
        loginUsernameTextField = new javax.swing.JTextField();
        loginButton = new javax.swing.JButton();
        registerHereButton = new javax.swing.JLabel();
        registerMsgLabel = new javax.swing.JLabel();
        registerPanel = new javax.swing.JPanel();
        registerLeftPanel = new javax.swing.JPanel();
        Logo1 = new javax.swing.JLabel();
        registerRightPanel = new javax.swing.JPanel();
        newAccountLabel = new javax.swing.JLabel();
        registerButton = new javax.swing.JButton();
        loginHereButton = new javax.swing.JLabel();
        loginMsgLabel = new javax.swing.JLabel();
        registerUsernameLabel = new javax.swing.JLabel();
        registerUsernameTextField = new javax.swing.JTextField();
        registerPasswordTextField = new javax.swing.JTextField();
        registerPasswordLabel = new javax.swing.JLabel();
        registerFullNameTextField = new javax.swing.JTextField();
        registerFullNameLabel = new javax.swing.JLabel();
        registerBankAccountTextField = new javax.swing.JTextField();
        registerBankAccountLabel = new javax.swing.JLabel();
        dayComboBox = new javax.swing.JComboBox<>();
        yearComboBox = new javax.swing.JComboBox<>();
        monthComboBox = new javax.swing.JComboBox<>();
        RegisterDateOfBirthLabel = new javax.swing.JLabel();
        portfolioPanel = new javax.swing.JPanel();
        portfolioLeftPanel = new javax.swing.JPanel();
        logo2 = new javax.swing.JLabel();
        accountInformationButton = new javax.swing.JButton();
        logoutButton = new javax.swing.JButton();
        investButton = new javax.swing.JButton();
        walletButton = new javax.swing.JButton();
        portfolioButton = new javax.swing.JButton();
        portfolioRightPanel = new javax.swing.JPanel();
        portfolioLabel = new javax.swing.JLabel();
        portfolioStatisticsLabel = new javax.swing.JLabel();
        portfolioInvestmentsLabel = new javax.swing.JLabel();
        portfolioInvestmentsInfoLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jPanel1 = new javax.swing.JPanel();
        portfolioStatsInfoLabel2 = new javax.swing.JLabel();
        portfolioStatsInfoLabel3 = new javax.swing.JLabel();
        portfolioStatsInfoLabel4 = new javax.swing.JLabel();
        portfolioStatsInfoLabel5 = new javax.swing.JLabel();
        portfolioStatsInfoLabel6 = new javax.swing.JLabel();
        portfolioStatsInfoLabel7 = new javax.swing.JLabel();
        portfolioStatsInfoLabel8 = new javax.swing.JLabel();
        portfolioStatsInfoLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Shareversity");
        setBackground(new java.awt.Color(253, 234, 239));
        getContentPane().setLayout(new java.awt.CardLayout());

        loginPanel.setLayout(new java.awt.GridLayout(1, 0));

        loginLeftPanel.setBackground(new java.awt.Color(253, 234, 239));
        loginLeftPanel.setForeground(new java.awt.Color(253, 234, 239));
        loginLeftPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/logo.png"))); // NOI18N
        loginLeftPanel.add(Logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, -40, 500, 764));

        loginPanel.add(loginLeftPanel);

        loginRightPanel.setBackground(new java.awt.Color(227, 97, 115));
        loginRightPanel.setForeground(new java.awt.Color(227, 97, 115));

        loginLabel.setFont(new java.awt.Font("Segoe UI Black", 0, 40)); // NOI18N
        loginLabel.setForeground(new java.awt.Color(253, 234, 239));
        loginLabel.setText("Log in");
        loginLabel.setToolTipText("");
        loginLabel.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        loginPasswordLabel.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        loginPasswordLabel.setForeground(new java.awt.Color(253, 234, 239));
        loginPasswordLabel.setText("Password");
        loginPasswordLabel.setToolTipText("");

        loginPasswordTextField.setBackground(new java.awt.Color(255, 255, 255));
        loginPasswordTextField.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        loginPasswordTextField.setBorder(null);
        loginPasswordTextField.setOpaque(true);
        loginPasswordTextField.setScrollOffset(5);
        loginPasswordTextField.setSelectionColor(new java.awt.Color(100, 72, 145));
        loginPasswordTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginPasswordTextFieldActionPerformed(evt);
            }
        });

        loginUsernameLabel.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        loginUsernameLabel.setForeground(new java.awt.Color(253, 234, 239));
        loginUsernameLabel.setText("Username");
        loginUsernameLabel.setToolTipText("");

        loginUsernameTextField.setBackground(new java.awt.Color(255, 255, 255));
        loginUsernameTextField.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        loginUsernameTextField.setBorder(null);
        loginUsernameTextField.setOpaque(true);
        loginUsernameTextField.setScrollOffset(5);
        loginUsernameTextField.setSelectionColor(new java.awt.Color(100, 72, 145));
        loginUsernameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginUsernameTextFieldActionPerformed(evt);
            }
        });

        loginButton.setBackground(new java.awt.Color(100, 72, 145));
        loginButton.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        loginButton.setForeground(new java.awt.Color(255, 255, 255));
        loginButton.setText("Login");
        loginButton.setBorder(null);
        loginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginButtonActionPerformed(evt);
            }
        });

        registerHereButton.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        registerHereButton.setForeground(new java.awt.Color(253, 234, 239));
        registerHereButton.setText("<HTML><U>Register here</U></HTML>");
        registerHereButton.setToolTipText("");
        registerHereButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                registerHereButtonMouseClicked(evt);
            }
        });

        registerMsgLabel.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        registerMsgLabel.setForeground(new java.awt.Color(253, 234, 239));
        registerMsgLabel.setText("Don't have an account? ");
        registerMsgLabel.setToolTipText("");

        org.jdesktop.layout.GroupLayout loginRightPanelLayout = new org.jdesktop.layout.GroupLayout(loginRightPanel);
        loginRightPanel.setLayout(loginRightPanelLayout);
        loginRightPanelLayout.setHorizontalGroup(
            loginRightPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(loginRightPanelLayout.createSequentialGroup()
                .add(61, 61, 61)
                .add(loginRightPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(loginPasswordLabel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 97, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(loginPasswordTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 399, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(loginUsernameLabel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 97, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(loginUsernameTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 394, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(loginRightPanelLayout.createSequentialGroup()
                        .add(141, 141, 141)
                        .add(loginLabel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 122, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(loginRightPanelLayout.createSequentialGroup()
                        .add(27, 27, 27)
                        .add(loginRightPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(loginRightPanelLayout.createSequentialGroup()
                                .add(registerMsgLabel)
                                .add(3, 3, 3)
                                .add(registerHereButton, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                            .add(loginButton, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 339, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        loginRightPanelLayout.setVerticalGroup(
            loginRightPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(loginRightPanelLayout.createSequentialGroup()
                .add(178, 178, 178)
                .add(loginLabel)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(loginUsernameLabel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 56, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(loginUsernameTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 45, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(loginPasswordLabel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 56, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(loginPasswordTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 45, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(56, 56, 56)
                .add(loginButton, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 56, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(loginRightPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(registerHereButton, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 56, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(registerMsgLabel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 56, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(125, Short.MAX_VALUE))
        );

        loginPanel.add(loginRightPanel);

        getContentPane().add(loginPanel, "card2");

        registerPanel.setLayout(new java.awt.GridLayout(1, 0));

        registerLeftPanel.setBackground(new java.awt.Color(253, 234, 239));
        registerLeftPanel.setForeground(new java.awt.Color(253, 234, 239));
        registerLeftPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Logo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/logo.png"))); // NOI18N
        registerLeftPanel.add(Logo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, -40, 500, 764));

        registerPanel.add(registerLeftPanel);

        registerRightPanel.setBackground(new java.awt.Color(227, 97, 115));
        registerRightPanel.setForeground(new java.awt.Color(227, 97, 115));

        newAccountLabel.setFont(new java.awt.Font("Segoe UI Black", 0, 40)); // NOI18N
        newAccountLabel.setForeground(new java.awt.Color(253, 234, 239));
        newAccountLabel.setText("New Account");
        newAccountLabel.setToolTipText("");
        newAccountLabel.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        registerButton.setBackground(new java.awt.Color(100, 72, 145));
        registerButton.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        registerButton.setForeground(new java.awt.Color(255, 255, 255));
        registerButton.setText("Register");
        registerButton.setBorder(null);
        registerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerButtonActionPerformed(evt);
            }
        });

        loginHereButton.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        loginHereButton.setForeground(new java.awt.Color(253, 234, 239));
        loginHereButton.setText("<HTML><U>Login here</U></HTML>");
        loginHereButton.setToolTipText("");
        loginHereButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loginHereButtonMouseClicked(evt);
            }
        });

        loginMsgLabel.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        loginMsgLabel.setForeground(new java.awt.Color(253, 234, 239));
        loginMsgLabel.setText("Already have an account?");
        loginMsgLabel.setToolTipText("");

        registerUsernameLabel.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        registerUsernameLabel.setForeground(new java.awt.Color(253, 234, 239));
        registerUsernameLabel.setText("Username");
        registerUsernameLabel.setToolTipText("");

        registerUsernameTextField.setBackground(new java.awt.Color(255, 255, 255));
        registerUsernameTextField.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        registerUsernameTextField.setBorder(null);
        registerUsernameTextField.setOpaque(true);
        registerUsernameTextField.setScrollOffset(5);
        registerUsernameTextField.setSelectionColor(new java.awt.Color(100, 72, 145));
        registerUsernameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerUsernameTextFieldActionPerformed(evt);
            }
        });

        registerPasswordTextField.setBackground(new java.awt.Color(255, 255, 255));
        registerPasswordTextField.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        registerPasswordTextField.setBorder(null);
        registerPasswordTextField.setOpaque(true);
        registerPasswordTextField.setScrollOffset(5);
        registerPasswordTextField.setSelectionColor(new java.awt.Color(100, 72, 145));
        registerPasswordTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerPasswordTextFieldActionPerformed(evt);
            }
        });

        registerPasswordLabel.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        registerPasswordLabel.setForeground(new java.awt.Color(253, 234, 239));
        registerPasswordLabel.setText("Password");
        registerPasswordLabel.setToolTipText("");

        registerFullNameTextField.setBackground(new java.awt.Color(255, 255, 255));
        registerFullNameTextField.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        registerFullNameTextField.setBorder(null);
        registerFullNameTextField.setOpaque(true);
        registerFullNameTextField.setScrollOffset(5);
        registerFullNameTextField.setSelectionColor(new java.awt.Color(100, 72, 145));
        registerFullNameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerFullNameTextFieldActionPerformed(evt);
            }
        });

        registerFullNameLabel.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        registerFullNameLabel.setForeground(new java.awt.Color(253, 234, 239));
        registerFullNameLabel.setText("Full Name");
        registerFullNameLabel.setToolTipText("");

        registerBankAccountTextField.setBackground(new java.awt.Color(255, 255, 255));
        registerBankAccountTextField.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        registerBankAccountTextField.setBorder(null);
        registerBankAccountTextField.setOpaque(true);
        registerBankAccountTextField.setScrollOffset(5);
        registerBankAccountTextField.setSelectionColor(new java.awt.Color(100, 72, 145));
        registerBankAccountTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerBankAccountTextFieldActionPerformed(evt);
            }
        });

        registerBankAccountLabel.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        registerBankAccountLabel.setForeground(new java.awt.Color(253, 234, 239));
        registerBankAccountLabel.setText("Bank Account Number");
        registerBankAccountLabel.setToolTipText("");

        dayComboBox.setBackground(new java.awt.Color(255, 255, 255));
        dayComboBox.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        dayComboBox.setForeground(new java.awt.Color(51, 51, 51));
        dayComboBox.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dayComboBoxMouseClicked(evt);
            }
        });
        dayComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dayComboBoxActionPerformed(evt);
            }
        });

        yearComboBox.setBackground(new java.awt.Color(255, 255, 255));
        yearComboBox.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        yearComboBox.setForeground(new java.awt.Color(51, 51, 51));
        yearComboBox.setModel(this.generateYearArray());
        yearComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yearComboBoxActionPerformed(evt);
            }
        });

        monthComboBox.setBackground(new java.awt.Color(255, 255, 255));
        monthComboBox.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        monthComboBox.setForeground(new java.awt.Color(51, 51, 51));
        monthComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December" }));
        monthComboBox.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                monthComboBoxMouseClicked(evt);
            }
        });
        monthComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                monthComboBoxActionPerformed(evt);
            }
        });

        RegisterDateOfBirthLabel.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        RegisterDateOfBirthLabel.setForeground(new java.awt.Color(253, 234, 239));
        RegisterDateOfBirthLabel.setText("Date of birth");
        RegisterDateOfBirthLabel.setToolTipText("");

        org.jdesktop.layout.GroupLayout registerRightPanelLayout = new org.jdesktop.layout.GroupLayout(registerRightPanel);
        registerRightPanel.setLayout(registerRightPanelLayout);
        registerRightPanelLayout.setHorizontalGroup(
            registerRightPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(registerRightPanelLayout.createSequentialGroup()
                .addContainerGap(60, Short.MAX_VALUE)
                .add(registerRightPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, registerRightPanelLayout.createSequentialGroup()
                        .add(registerRightPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(registerButton, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 339, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(registerRightPanelLayout.createSequentialGroup()
                                .add(loginMsgLabel)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(loginHereButton, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                        .add(83, 83, 83))
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, registerRightPanelLayout.createSequentialGroup()
                        .add(registerRightPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(org.jdesktop.layout.GroupLayout.TRAILING, registerRightPanelLayout.createSequentialGroup()
                                .add(newAccountLabel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 274, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .add(61, 61, 61))
                            .add(org.jdesktop.layout.GroupLayout.TRAILING, registerRightPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                .add(registerFullNameLabel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 97, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .add(registerFullNameTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 399, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .add(registerPasswordLabel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 97, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .add(registerPasswordTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 399, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .add(registerUsernameLabel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 97, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .add(registerUsernameTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 399, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .add(registerRightPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                                    .add(registerRightPanelLayout.createSequentialGroup()
                                        .add(dayComboBox, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 108, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                                        .add(monthComboBox, 0, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                                        .add(yearComboBox, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 111, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                    .add(registerBankAccountTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 399, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                .add(RegisterDateOfBirthLabel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 155, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .add(registerBankAccountLabel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 232, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                        .add(51, 51, 51))))
        );
        registerRightPanelLayout.setVerticalGroup(
            registerRightPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(registerRightPanelLayout.createSequentialGroup()
                .addContainerGap(89, Short.MAX_VALUE)
                .add(newAccountLabel)
                .add(5, 5, 5)
                .add(registerUsernameLabel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 29, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(registerUsernameTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 45, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(registerPasswordLabel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 29, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(registerPasswordTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 45, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(registerFullNameLabel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 29, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(registerFullNameTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 45, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(registerBankAccountLabel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 29, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(registerBankAccountTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 48, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(RegisterDateOfBirthLabel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 29, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(registerRightPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, monthComboBox, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 48, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(registerRightPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                        .add(dayComboBox, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 48, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(yearComboBox, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 48, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .add(18, 18, 18)
                .add(registerButton, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 56, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(registerRightPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(loginHereButton, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 56, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(loginMsgLabel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 56, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(49, 49, 49))
        );

        registerPanel.add(registerRightPanel);

        getContentPane().add(registerPanel, "card3");

        portfolioPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        portfolioLeftPanel.setBackground(new java.awt.Color(253, 234, 239));
        portfolioLeftPanel.setForeground(new java.awt.Color(253, 234, 239));
        portfolioLeftPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logo2.setIcon(resizeImage(logo2, "/resources/logo.png", 262, 169));
        portfolioLeftPanel.add(logo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 280, 189));

        accountInformationButton.setBackground(new java.awt.Color(203, 75, 93));
        accountInformationButton.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        accountInformationButton.setForeground(new java.awt.Color(255, 255, 255));
        accountInformationButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/accountInfoIcon.png"))); // NOI18N
        accountInformationButton.setText("  Account Information");
        accountInformationButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        accountInformationButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accountInformationButtonActionPerformed(evt);
            }
        });
        portfolioLeftPanel.add(accountInformationButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 420, 271, 45));

        logoutButton.setBackground(new java.awt.Color(54, 54, 54));
        logoutButton.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        logoutButton.setForeground(new java.awt.Color(255, 255, 255));
        logoutButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/logoutIcon.png"))); // NOI18N
        logoutButton.setText("     Log out");
        logoutButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        logoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutButtonActionPerformed(evt);
            }
        });
        portfolioLeftPanel.add(logoutButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 640, 210, 45));

        investButton.setBackground(new java.awt.Color(203, 75, 93));
        investButton.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        investButton.setForeground(new java.awt.Color(255, 255, 255));
        investButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/investIcon.png"))); // NOI18N
        investButton.setText("     Invest");
        investButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        investButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                investButtonActionPerformed(evt);
            }
        });
        portfolioLeftPanel.add(investButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, 271, 45));

        walletButton.setBackground(new java.awt.Color(203, 75, 93));
        walletButton.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        walletButton.setForeground(new java.awt.Color(255, 255, 255));
        walletButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/walletIcon.png"))); // NOI18N
        walletButton.setText("    Wallet");
        walletButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        walletButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                walletButtonActionPerformed(evt);
            }
        });
        portfolioLeftPanel.add(walletButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, 271, 45));

        portfolioButton.setBackground(new java.awt.Color(88, 88, 88));
        portfolioButton.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        portfolioButton.setForeground(new java.awt.Color(255, 255, 255));
        portfolioButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/portfolioIcon.png"))); // NOI18N
        portfolioButton.setText("     Portfolio");
        portfolioButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        portfolioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                portfolioButtonActionPerformed(evt);
            }
        });
        portfolioLeftPanel.add(portfolioButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 271, 45));

        portfolioPanel.add(portfolioLeftPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 293, 764));

        portfolioRightPanel.setBackground(new java.awt.Color(227, 97, 115));
        portfolioRightPanel.setForeground(new java.awt.Color(227, 97, 115));

        portfolioLabel.setFont(new java.awt.Font("Segoe UI Black", 0, 40)); // NOI18N
        portfolioLabel.setForeground(new java.awt.Color(253, 234, 239));
        portfolioLabel.setText("Portfolio");
        portfolioLabel.setToolTipText("");
        portfolioLabel.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        portfolioStatisticsLabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        portfolioStatisticsLabel.setForeground(new java.awt.Color(253, 234, 239));
        portfolioStatisticsLabel.setText("Portfolio Statistics");
        portfolioStatisticsLabel.setToolTipText("");

        portfolioInvestmentsLabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        portfolioInvestmentsLabel.setForeground(new java.awt.Color(253, 234, 239));
        portfolioInvestmentsLabel.setText("Portfolio Investments");
        portfolioInvestmentsLabel.setToolTipText("");

        portfolioInvestmentsInfoLabel.setFont(new java.awt.Font("Segoe UI Semilight", 2, 18)); // NOI18N
        portfolioInvestmentsInfoLabel.setForeground(new java.awt.Color(253, 234, 239));
        portfolioInvestmentsInfoLabel.setText("<HTML><b>Click an investment to view more information and for the option sell shares");
        portfolioInvestmentsInfoLabel.setToolTipText("");

        jList1.setBackground(new java.awt.Color(255, 255, 255));
        jList1.setFont(new java.awt.Font("Segoe UI Black", 0, 15)); // NOI18N
        jList1.setForeground(new java.awt.Color(88, 88, 88));
        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Delicious Bites | Profit: $-1.40 | ROI: -0.0155% | Value: $88.60", "Delicious Bites | Profit: $-1.40 | ROI: -0.0155% | Value: $88.60", "Delicious Bites | Profit: $-1.40 | ROI: -0.0155% | Value: $88.60", "Delicious Bites | Profit: $-1.40 | ROI: -0.0155% | Value: $88.60", "Delicious Bites | Profit: $-1.40 | ROI: -0.0155% | Value: $88.60", "Delicious Bites | Profit: $-1.40 | ROI: -0.0155% | Value: $88.60", "Delicious Bites | Profit: $-1.40 | ROI: -0.0155% | Value: $88.60", "Delicious Bites | Profit: $-1.40 | ROI: -0.0155% | Value: $88.60", "Delicious Bites | Profit: $-1.40 | ROI: -0.0155% | Value: $88.60", "Delicious Bites | Profit: $-1.40 | ROI: -0.0155% | Value: $88.60", "Delicious Bites | Profit: $-1.40 | ROI: -0.0155% | Value: $88.60", "Delicious Bites | Profit: $-1.40 | ROI: -0.0155% | Value: $88.60", "Delicious Bites | Profit: $-1.40 | ROI: -0.0155% | Value: $88.60", "Delicious Bites | Profit: $-1.40 | ROI: -0.0155% | Value: $88.60" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jList1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);
        jList1.setSelectionBackground(new java.awt.Color(153, 107, 229));
        jList1.setSelectionForeground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setViewportView(jList1);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        portfolioStatsInfoLabel2.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        portfolioStatsInfoLabel2.setForeground(new java.awt.Color(88, 88, 88));
        portfolioStatsInfoLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        portfolioStatsInfoLabel2.setText("$90.0");

        portfolioStatsInfoLabel3.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        portfolioStatsInfoLabel3.setForeground(new java.awt.Color(88, 88, 88));
        portfolioStatsInfoLabel3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        portfolioStatsInfoLabel3.setText("Total profit/loss:");

        portfolioStatsInfoLabel4.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        portfolioStatsInfoLabel4.setForeground(new java.awt.Color(88, 88, 88));
        portfolioStatsInfoLabel4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        portfolioStatsInfoLabel4.setText("Total amount invested:");

        portfolioStatsInfoLabel5.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        portfolioStatsInfoLabel5.setForeground(new java.awt.Color(88, 88, 88));
        portfolioStatsInfoLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        portfolioStatsInfoLabel5.setText("$-1.40");

        portfolioStatsInfoLabel6.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        portfolioStatsInfoLabel6.setForeground(new java.awt.Color(88, 88, 88));
        portfolioStatsInfoLabel6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        portfolioStatsInfoLabel6.setText("Total return on investment (ROI)");

        portfolioStatsInfoLabel7.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        portfolioStatsInfoLabel7.setForeground(new java.awt.Color(88, 88, 88));
        portfolioStatsInfoLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        portfolioStatsInfoLabel7.setText("-0.0155%");

        portfolioStatsInfoLabel8.setFont(new java.awt.Font("Segoe UI Black", 1, 16)); // NOI18N
        portfolioStatsInfoLabel8.setForeground(new java.awt.Color(88, 88, 88));
        portfolioStatsInfoLabel8.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        portfolioStatsInfoLabel8.setText("Total value:");

        portfolioStatsInfoLabel9.setFont(new java.awt.Font("Segoe UI Black", 1, 16)); // NOI18N
        portfolioStatsInfoLabel9.setForeground(new java.awt.Color(88, 88, 88));
        portfolioStatsInfoLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        portfolioStatsInfoLabel9.setText("$88.60");

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .add(25, 25, 25)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(portfolioStatsInfoLabel8, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 264, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(portfolioStatsInfoLabel9, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 256, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                        .add(jPanel1Layout.createSequentialGroup()
                            .add(portfolioStatsInfoLabel6, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 264, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                            .add(portfolioStatsInfoLabel7, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 256, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .add(jPanel1Layout.createSequentialGroup()
                            .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                                .add(portfolioStatsInfoLabel3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 264, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .add(portfolioStatsInfoLabel4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 264, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                            .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                .add(portfolioStatsInfoLabel2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 256, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .add(portfolioStatsInfoLabel5, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 256, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .add(31, 31, 31)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(portfolioStatsInfoLabel2)
                    .add(portfolioStatsInfoLabel4))
                .add(30, 30, 30)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(portfolioStatsInfoLabel3)
                    .add(portfolioStatsInfoLabel5))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(portfolioStatsInfoLabel6)
                    .add(portfolioStatsInfoLabel7))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(portfolioStatsInfoLabel8)
                    .add(portfolioStatsInfoLabel9))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        org.jdesktop.layout.GroupLayout portfolioRightPanelLayout = new org.jdesktop.layout.GroupLayout(portfolioRightPanel);
        portfolioRightPanel.setLayout(portfolioRightPanelLayout);
        portfolioRightPanelLayout.setHorizontalGroup(
            portfolioRightPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, portfolioRightPanelLayout.createSequentialGroup()
                .addContainerGap(77, Short.MAX_VALUE)
                .add(portfolioRightPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, portfolioRightPanelLayout.createSequentialGroup()
                        .add(portfolioLabel)
                        .add(268, 268, 268))
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, portfolioRightPanelLayout.createSequentialGroup()
                        .add(portfolioRightPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                            .add(portfolioStatisticsLabel)
                            .add(portfolioInvestmentsLabel)
                            .add(portfolioInvestmentsInfoLabel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 582, Short.MAX_VALUE)
                            .add(jScrollPane1)
                            .add(jPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .add(72, 72, 72))))
        );
        portfolioRightPanelLayout.setVerticalGroup(
            portfolioRightPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(portfolioRightPanelLayout.createSequentialGroup()
                .add(54, 54, 54)
                .add(portfolioLabel)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(portfolioInvestmentsLabel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 26, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(portfolioInvestmentsInfoLabel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(18, 18, 18)
                .add(portfolioStatisticsLabel)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(152, Short.MAX_VALUE))
        );

        portfolioPanel.add(portfolioRightPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 0, 731, 764));

        getContentPane().add(portfolioPanel, "card2");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loginPasswordTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginPasswordTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_loginPasswordTextFieldActionPerformed

    private void loginUsernameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginUsernameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_loginUsernameTextFieldActionPerformed

    private void loginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginButtonActionPerformed
        cardLayout.show(this.getContentPane(),"portfolioPanel");
        System.out.println("Login button clicked");
    }//GEN-LAST:event_loginButtonActionPerformed

    private void registerHereButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registerHereButtonMouseClicked
        cardLayout.show(this.getContentPane(),"registerPanel");
        System.out.println("register Here button clicked");
    }//GEN-LAST:event_registerHereButtonMouseClicked

    private void registerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_registerButtonActionPerformed

    private void loginHereButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginHereButtonMouseClicked
        
        cardLayout.show(this.getContentPane(),"loginPanel");
        System.out.println("login Here button clicked");
    }//GEN-LAST:event_loginHereButtonMouseClicked

    private void registerUsernameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerUsernameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_registerUsernameTextFieldActionPerformed

    private void registerPasswordTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerPasswordTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_registerPasswordTextFieldActionPerformed

    private void registerFullNameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerFullNameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_registerFullNameTextFieldActionPerformed

    private void registerBankAccountTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerBankAccountTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_registerBankAccountTextFieldActionPerformed

    private void dayComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dayComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dayComboBoxActionPerformed

    private void yearComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yearComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_yearComboBoxActionPerformed

    
    private void monthComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_monthComboBoxActionPerformed

        updateDayComboBox();
        System.out.println("days updated");
    }//GEN-LAST:event_monthComboBoxActionPerformed

    private void dayComboBoxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dayComboBoxMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_dayComboBoxMouseClicked

    private void monthComboBoxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_monthComboBoxMouseClicked
        //updateDayComboBox();
        //System.out.println("days updated");
    }//GEN-LAST:event_monthComboBoxMouseClicked

    private void accountInformationButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accountInformationButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_accountInformationButtonActionPerformed

    private void logoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutButtonActionPerformed
        cardLayout.show(this.getContentPane(),"loginPanel");
        System.out.println("login Here button clicked");
    }//GEN-LAST:event_logoutButtonActionPerformed

    private void investButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_investButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_investButtonActionPerformed

    private void walletButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_walletButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_walletButtonActionPerformed

    private void portfolioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_portfolioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_portfolioButtonActionPerformed

    /*
        This method gets this year and gets the previous 100 years as a list of years as a DefaultComboBoxModel (for registering year of birth)
    */
    private static DefaultComboBoxModel<String> generateYearArray()
    {
        int currentYear = Calendar.getInstance().get(Calendar.YEAR); 
        
        DefaultComboBoxModel<String> yearArray = new DefaultComboBoxModel<String>();

        int minYear = currentYear-100;
        for (int year = currentYear; year >= minYear; year--)
        {
            yearArray.addElement(String.valueOf(year));
        }
        
        return yearArray;
    }
    
    /*
        This method gets the days in a month so that they appropriately correspond to month-day differences (28,30,31)
    */
    private static int getDaysInMonth(int month)
    {
        Calendar calendar = Calendar.getInstance();
        calendar.set(Calendar.MONTH, month);
        return calendar.getActualMaximum(Calendar.DAY_OF_MONTH);
    }
    
    /*
        This method updates the number of days set to a month selected in the combo box
    */
    private static void updateDayComboBox() 
    {
        int selectedMonthIndex = monthComboBox.getSelectedIndex();
        int daysInMonth = getDaysInMonth(selectedMonthIndex);

        DefaultComboBoxModel<String> model = new DefaultComboBoxModel<>();
        for (int i = 1; i <= daysInMonth; i++) {
            model.addElement(String.valueOf(i));
        }

        dayComboBox.setModel(model); 
    }
    
    /*
        This method makes an inputted image resizable according to inputted label dimensions
    */
    private ImageIcon resizeImage(javax.swing.JLabel label, String imgPath, int w, int h)
    {
        javax.swing.ImageIcon img = new javax.swing.ImageIcon(getClass().getResource(imgPath));

        Image resizableImg = img.getImage().getScaledInstance(w, h, Image.SCALE_SMOOTH); // make img resizable by getting scaled instance & setting to label dimensions
        ImageIcon imageIcon = new ImageIcon(resizableImg); // create new ImageIcon from resizable img
        
        return imageIcon;
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ShareversityGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ShareversityGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ShareversityGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ShareversityGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ShareversityGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Logo;
    private javax.swing.JLabel Logo1;
    private javax.swing.JLabel RegisterDateOfBirthLabel;
    private javax.swing.JButton accountInformationButton;
    private static javax.swing.JComboBox<String> dayComboBox;
    private javax.swing.JButton investButton;
    private javax.swing.JList<String> jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton loginButton;
    private javax.swing.JLabel loginHereButton;
    private javax.swing.JLabel loginLabel;
    private javax.swing.JPanel loginLeftPanel;
    private javax.swing.JLabel loginMsgLabel;
    private javax.swing.JPanel loginPanel;
    private javax.swing.JLabel loginPasswordLabel;
    private javax.swing.JTextField loginPasswordTextField;
    private javax.swing.JPanel loginRightPanel;
    private javax.swing.JLabel loginUsernameLabel;
    private javax.swing.JTextField loginUsernameTextField;
    private javax.swing.JLabel logo2;
    private javax.swing.JButton logoutButton;
    private static javax.swing.JComboBox<String> monthComboBox;
    private javax.swing.JLabel newAccountLabel;
    private javax.swing.JButton portfolioButton;
    private javax.swing.JLabel portfolioInvestmentsInfoLabel;
    private javax.swing.JLabel portfolioInvestmentsLabel;
    private javax.swing.JLabel portfolioLabel;
    private javax.swing.JPanel portfolioLeftPanel;
    private javax.swing.JPanel portfolioPanel;
    private javax.swing.JPanel portfolioRightPanel;
    private javax.swing.JLabel portfolioStatisticsLabel;
    private javax.swing.JLabel portfolioStatsInfoLabel2;
    private javax.swing.JLabel portfolioStatsInfoLabel3;
    private javax.swing.JLabel portfolioStatsInfoLabel4;
    private javax.swing.JLabel portfolioStatsInfoLabel5;
    private javax.swing.JLabel portfolioStatsInfoLabel6;
    private javax.swing.JLabel portfolioStatsInfoLabel7;
    private javax.swing.JLabel portfolioStatsInfoLabel8;
    private javax.swing.JLabel portfolioStatsInfoLabel9;
    private javax.swing.JLabel registerBankAccountLabel;
    private javax.swing.JTextField registerBankAccountTextField;
    private javax.swing.JButton registerButton;
    private javax.swing.JLabel registerFullNameLabel;
    private javax.swing.JTextField registerFullNameTextField;
    private javax.swing.JLabel registerHereButton;
    private javax.swing.JPanel registerLeftPanel;
    private javax.swing.JLabel registerMsgLabel;
    private javax.swing.JPanel registerPanel;
    private javax.swing.JLabel registerPasswordLabel;
    private javax.swing.JTextField registerPasswordTextField;
    private javax.swing.JPanel registerRightPanel;
    private javax.swing.JLabel registerUsernameLabel;
    private javax.swing.JTextField registerUsernameTextField;
    private javax.swing.JButton walletButton;
    private javax.swing.JComboBox<String> yearComboBox;
    // End of variables declaration//GEN-END:variables
    private CardLayout cardLayout;
}
